function [f,fz,fzi] = autoGen_objective_with_tension(xQ,yQ,zQ,dxQ,dyQ,dzQ,phi,theta,psi,dphi,dtheta,dpsi,xL,yL,zL,dxL,dyL,dzL,f,tauphi,tautheta,taupsi,R,Q,T)
%AUTOGEN_OBJECTIVE_WITH_TENSION
%    [F,FZ,FZI] = AUTOGEN_OBJECTIVE_WITH_TENSION(XQ,YQ,ZQ,DXQ,DYQ,DZQ,PHI,THETA,PSI,DPHI,DTHETA,DPSI,XL,YL,ZL,DXL,DYL,DZL,F,TAUPHI,TAUTHETA,TAUPSI,R,Q,T)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    13-Dec-2017 20:47:28

f = Q.*dphi.^2+Q.*dpsi.^2+Q.*dtheta.^2+Q.*dxL.^2+Q.*dxQ.^2+Q.*dyL.^2+Q.*dyQ.^2+Q.*dzL.^2+Q.*dzQ.^2+R.*f.^2+Q.*phi.^2+Q.*psi.^2+Q.*theta.^2+R.*tauphi.^2+R.*taupsi.^2+R.*tautheta.^2+Q.*xL.^2+Q.*xQ.^2+Q.*yL.^2+Q.*yQ.^2+Q.*zL.^2+Q.*zQ.^2;
if nargout > 1
    fz = [Q.*xQ.*2.0;Q.*yQ.*2.0;Q.*zQ.*2.0;Q.*dxQ.*2.0;Q.*dyQ.*2.0;Q.*dzQ.*2.0;Q.*phi.*2.0;Q.*theta.*2.0;Q.*psi.*2.0;Q.*dphi.*2.0;Q.*dtheta.*2.0;Q.*dpsi.*2.0;Q.*xL.*2.0;Q.*yL.*2.0;Q.*zL.*2.0;Q.*dxL.*2.0;Q.*dyL.*2.0;Q.*dzL.*2.0;R.*f.*2.0;R.*tauphi.*2.0;R.*tautheta.*2.0;R.*taupsi.*2.0];
end
if nargout > 2
    fzi = [1.0;2.0;3.0;4.0;5.0;6.0;7.0;8.0;9.0;1.0e1;1.1e1;1.2e1;1.3e1;1.4e1;1.5e1;1.6e1;1.7e1;1.8e1;1.9e1;2.0e1;2.1e1;2.2e1];
end
