function P = autoGen_forwardKinematics_with_tension(xQ,yQ,zQ,dxQ,dyQ,dzQ,phi,theta,psi,dphi,dtheta,dpsi,xL,yL,zL,dxL,dyL,dzL,l)
%AUTOGEN_FORWARDKINEMATICS_WITH_TENSION
%    P = AUTOGEN_FORWARDKINEMATICS_WITH_TENSION(XQ,YQ,ZQ,DXQ,DYQ,DZQ,PHI,THETA,PSI,DPHI,DTHETA,DPSI,XL,YL,ZL,DXL,DYL,DZL,L)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    13-Dec-2017 20:47:28

t2 = cos(phi);
t3 = cos(psi);
t4 = sin(phi);
t5 = sin(psi);
t6 = sin(theta);
t7 = cos(theta);
t8 = t3.*t4.*t6.*4.618520267e-2;
t9 = t2.*t3.*4.618520267e-2;
t10 = t4.*t5.*t6.*4.618520267e-2;
t11 = t4.*t7.*4.618520267e-2;
t12 = t3.*t7.*4.618520267e-2;
t13 = t5.*t7.*4.618520267e-2;
P = reshape([xQ,xL,t8+xQ-t2.*t5.*4.618520267e-2,t12+xQ,-t8+xQ+t2.*t5.*4.618520267e-2,-t12+xQ,yQ,yL,t9+t10+yQ,t13+yQ,-t9-t10+yQ,-t13+yQ,zQ,zL,t11+zQ,t6.*(-4.618520267e-2)+zQ,-t11+zQ,t6.*4.618520267e-2+zQ],[6,3]);
