function [f,fz,fzi] = autoGen_objective(x,y,z,dx,dy,dz,phi,theta,psi,dphi,dtheta,dpsi,phiBall,thetaBall,dphiBall,dthetaBall,T,tauphi,tautheta,taupsi,R1,R2,R3,R4,Q1,Q2,Q3,Q4,Q5,Q6,Q7,Q8,Q9,Q10,Q11,Q12,Q13,Q14,Q15,Q16)
%AUTOGEN_OBJECTIVE
%    [F,FZ,FZI] = AUTOGEN_OBJECTIVE(X,Y,Z,DX,DY,DZ,PHI,THETA,PSI,DPHI,DTHETA,DPSI,PHIBALL,THETABALL,DPHIBALL,DTHETABALL,T,TAUPHI,TAUTHETA,TAUPSI,R1,R2,R3,R4,Q1,Q2,Q3,Q4,Q5,Q6,Q7,Q8,Q9,Q10,Q11,Q12,Q13,Q14,Q15,Q16)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    14-Dec-2017 13:14:54

f = R1.*T.^2+Q10.*dphi.^2+Q15.*dphiBall.^2+Q12.*dpsi.^2+Q11.*dtheta.^2+Q16.*dthetaBall.^2+Q4.*dx.^2+Q5.*dy.^2+Q6.*dz.^2+Q7.*phi.^2+Q13.*phiBall.^2+Q9.*psi.^2+Q14.*thetaBall.^2+Q8.*theta.^2+R2.*tauphi.^2+R4.*taupsi.^2+R3.*tautheta.^2+Q1.*x.^2+Q2.*y.^2+Q3.*z.^2;
if nargout > 1
    fz = [Q1.*x.*2.0;Q2.*y.*2.0;Q3.*z.*2.0;Q4.*dx.*2.0;Q5.*dy.*2.0;Q6.*dz.*2.0;Q7.*phi.*2.0;Q8.*theta.*2.0;Q9.*psi.*2.0;Q10.*dphi.*2.0;Q11.*dtheta.*2.0;Q12.*dpsi.*2.0;Q13.*phiBall.*2.0;Q14.*thetaBall.*2.0;Q15.*dphiBall.*2.0;Q16.*dthetaBall.*2.0;R1.*T.*2.0;R2.*tauphi.*2.0;R3.*tautheta.*2.0;R4.*taupsi.*2.0];
end
if nargout > 2
    fzi = [1.0;2.0;3.0;4.0;5.0;6.0;7.0;8.0;9.0;1.0e1;1.1e1;1.2e1;1.3e1;1.4e1;1.5e1;1.6e1;1.7e1;1.8e1;1.9e1;2.0e1];
end
