function P = autoGen_forwardKinematics(x,y,z,dx,dy,dz,phi,theta,psi,dphi,dtheta,dpsi,phiBall,thetaBall,dphiBall,dthetaBall)
%AUTOGEN_FORWARDKINEMATICS
%    P = AUTOGEN_FORWARDKINEMATICS(X,Y,Z,DX,DY,DZ,PHI,THETA,PSI,DPHI,DTHETA,DPSI,PHIBALL,THETABALL,DPHIBALL,DTHETABALL)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    14-Dec-2017 13:14:54

t2 = cos(phiBall);
t3 = cos(phi);
t4 = cos(psi);
t5 = sin(phi);
t6 = sin(psi);
t7 = sin(theta);
t8 = cos(theta);
t9 = t4.*t5.*t7.*4.618520267e-2;
t10 = t3.*t4.*4.618520267e-2;
t11 = t5.*t6.*t7.*4.618520267e-2;
t12 = t5.*t8.*4.618520267e-2;
t13 = t4.*t8.*4.618520267e-2;
t14 = t6.*t8.*4.618520267e-2;
P = reshape([x,x+t2.*sin(thetaBall).*(3.0./1.0e1),t9+x-t3.*t6.*4.618520267e-2,t13+x,-t9+x+t3.*t6.*4.618520267e-2,-t13+x,y,y-sin(phiBall).*(3.0./1.0e1),t10+t11+y,t14+y,-t10-t11+y,-t14+y,z,z+t2.*cos(thetaBall).*(3.0./1.0e1),t12+z,t7.*(-4.618520267e-2)+z,-t12+z,t7.*4.618520267e-2+z],[6,3]);
